### 异常处理的基本概念

#### 错误与异常

异常处理可以理解为发现程序中的错误,对不同的错误采用不同的处理方式~

**程序错误?**

也就有三种:语法错,语义错,逻辑错

**语法错误**

这个就是违反了程序设计语言的语法规则而产生的错误,这种错误编译的时候就可以直接发现

**语义错误**

程序的语法正确,也就是说通过了编译,如果语义存在错误,如输入格式错,除数为0错,给变量赋值超出其允许范围等... 

语义错的时候,编译系统不能发现他们

**逻辑错误**

这个呢就更好理解了,其实就可以理解为你分析程序的逻辑不对,像一些算法,上下的逻辑不同~



Java系统根据程序错误的严重程度的不同,程序运行时出的错分为两类:错误和异常

错误就是在程序执行过程中所遇到的硬件或操作系统的错误,内存溢出,虚拟机错误,这些都会导致程序无法运行,而且程序本身不能处理错误,只能依靠外界干预,否则一直非正常状态.如没找到.class文件,或文件中没有main( )方法等,这样程序不能运行

异常的话,硬件和操作系统是正常的,程序遇到的运行错

异常对于程序而言是非致命性的,虽然也会导致程序非正常终止,但Java语言的异常处理机制使程序自身能够捕捉和处理异常

#### Java语言的异常处理机制

Java语言的所有异常都是以类的方式存在的,除了内置的异常类之外,Java语言也允许用户自己定义异常类

生成异常对象并把它提交给运行系统的过程成为抛出异常,这个对象可能由应用系统本身产生,也可能由Java虚拟机产生,这取决于产生异常的类型

异常对象包含--->异常事件类型以及发生异常时应用程序目前的状态和调用过程等必要的信息

异常抛出后?--->运行系统从生成异常对象的代码开始,沿方法的调用栈逐层回溯查找,直到找到包含相应异常处理的方法,就是捕捉异常



简单点说,发现异常的代码可以"抛出"一个异常,运行系统"捕捉"该异常,并交由程序员编写的相应代码进行异常处理

### 异常处理类

每一种异常类都代表一种运行错误,所以说,Java语言的异常类是处理运行时错误的特殊类,类中包含了该运行错误的信息和处理错误的方法等内容

异常类层次的最上层有一个单独的类叫作Throwable,它是java.lang包中的一个类--->用来表示所有的异常情况,该类派生了两个子类java.lang.Error和java.lang.Exception

Error子类由系统保留,因为该类定义了那些应用程序通常没法捕捉到的错误

Error类及其子类的对象是由Java虚拟机生成并抛出给系统,这种错误有内存溢出出错,栈溢出错,动态链接错等...

这种异常应用程序通常不处理,都是由操作系统处理的~

而Exception子类则是供应用程序使用的,它是用户程序能够捕捉到的异常情况~ 说的异常一般指的就是这个!

### 异常的处理

异常处理是通过try、catch、finally、throw、throws五个关键字来实现的

**异常的产生**

```java
package Main;

public class App9_1 {
    public static void main(String[] args) {
        int i;
        int[] a = { 1, 2, 3, 4 };
        for (i = 0; i < 5; i++)
            System.out.println(a[i]);
        System.out.println(5 / 0);
    }
}
```

**使用try-catch-finally语句捕获和处理异常**

```java
package Main;

public class App9_2 {
    public static void main(String[] args) {
        int i;
        int[] a = { 1, 2, 3, 4 };
        for (i = 0; i < 5; i++) {
            try {
                System.out.println("a[" + i + "]/" + i + "=" + (a[i] / i));
            } catch (ArrayIndexOutOfBoundsException e) {
                System.out.print("捕捉到了数组下标越界异常");
            } catch (ArithmeticException e) {
                System.out.print("异常类名称是:" + e);
            } catch (Exception e) {
                System.out.println("捕捉" + e.getMessage() + "异常!");
            } finally {
                System.out.println("finally i=" + i);
            }
        }
        System.out.println("继续!!");
    }
}
```

### 抛出异常

有两种情况

1.系统自动抛出的异常

2.指定方法抛出异常

所有系统定义的运行时异常都可以由系统自动抛出,而指定方法抛出异常需要使用关键字throw或throws来明确指定在方法内抛出异常



**1.抛出异常的方法与调用方法处理异常**

抛出异常的方法

如果在一个方法内部的语句执行时可能引发某种异常,但是吧,我并不能确定如何处理,则此方法应声明抛出异常,表明该方法将不对这些异常进行处理,而由该方法的调用者负责处理

==方式一:==在方法体内使用throw语句抛出异常对象

throw 由异常类所产生的对象;

==方式二:==在方法头部添加throws子句表示方法将抛出异常

==[修饰符] 返回值类型 方法名([参数列表]) throws 异常类列表==

处理异常的方法

抛出了异常,怎么处理?  如果说方法内没有处理异常的语句,则系统就会将异常向上传递,由调用它的方法来处理这些异常,上一次没有怎么办,就一直想上寻找,一直可以追到main()方法   !!!必须要捕捉并处理异常,否则会出现错误



==我刚开始没明白表达的是什么意思,我直接看代码吧......==

```java
package Main;

public class App9_4 {
    public static double multi(int n) {
        if (n < 0)
            throw new IllegalArgumentException("求负数阶乘异常");
        double s = 1;
        for (int i = 1; i <= n; i++)
            s *= i;
        return s;
    }

    public static void main(String[] args) {
        try {
            int m = Integer.parseInt(args[0]);
            System.out.println(multi(m));
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("命令行中没提供参数!");
        } catch (NumberFormatException e) {
            System.out.println("应输入一个整数!");
        } catch (IllegalArgumentException e) {
            System.out.println("出现的异常是:" + e.toString());
        } finally {
            System.out.println("程序运行结束!");
        }
    }
}
```

==用这个例子来理解捕捉吧==

在main函数中调用了multi函数,在multi函数中,抛出了异常,但是并没有捕捉,所以main函数必须要有一个捕捉这个异常的代码~



**2.由方法抛出异常交系统处理**

对于程序需要处理的异常,一般编写try-catch-finally语句捕获并处理,而对于程序中无法处理必须交由系统处理的异常,由于系统直接调用的主方法main(),所以可以在主方法头使用throws子句声明抛出异常交系统处理

其实就是在方法声明中异常处理,抛出的是异常类型

==举个例子==

```java
package Main;

import java.io.*;

public class Test {
    public static void main(String[] args) throws IOException {
        FileInputStream fis = new FileInputStream("a.bat");
    }
}
```

这个就是让系统默认的异常处理机制去处理~

==再举个例子==

```java
package Main;

import java.io.*;

public class App9_6 {
    public static void main(String[] args) throws IOException {
        String str;
        BufferedReader buf;
        buf = new BufferedReader(new InputStreamReader(System.in));
        while (true) {
            try {
                System.out.print("请输入字符串");
                str = buf.readLine();
                if (str.length() > 0)
                    break;
                else
                    throw new IOException();
            } catch (IOException e) {
                System.out.println("必须输入字符串!!");
                continue;
            }
        }
        String s = str.toUpperCase();
        System.out.println("转换后的字符串为:" + s);
    }
}
```

==最后简单思考一下throw和throws....==

throws是告诉调用者,抛出一个什么样的异常,即异常的类型,我可以理解为声明；throw是真正抛出一个异常的实例,就是把这个异常抛出而不是简单声明异常

### 自动关闭资源的try语句

==try-with-resources---自动资源管理语句==

```java
//语句格式
try(声明或初始化资源的代码)
{
    使用资源对象res的语句
}
```

怎么理解呢? 其实就是括号里面就是声明和初始化的资源,可以一个,多个 中间用;隔开

注意的就是,不是所有的都可以自动关闭,只有实现java.lang.AutoCloseable接口的那些资源才可以自动关闭~

```java
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Scanner;

public class App9_7 {
    public static void main(String[] args) throws IOException {
        try (Scanner in = new Scanner(Paths.get("chapter9\\t.txt"))) {
            while (in.hasNext())
                System.out.println(in.nextLine());
        }
    }
}
```

看资源自动关闭没有,可以通过调试的方法,观察的比较详细~



### 自定义异常类

声明一个新的异常类 用户自定义的异常类必须是Throwable类的直接类或间接子类

==Java推荐用户自定义的异常类以Exception为直接父类,可以用系统自带的异常类或用户自己定义的异常类为父类==

==然后呢,为用户定义的异常类定义属性和方法或者覆盖父类的属性和方法,习惯上是用两个构造方法,一个无参构造,一个含有字符串型参数的构造方法~==

```java
//自定义的异常类
class CircleException extends Exception {
    double radius;

    CircleException(double r) {
        radius = r;
    }

    public String toString() {
        return "半径r=" + radius + "不是一个正数";
    }
}

class Circle {
    private double radius;

    public void setRadius(double r) throws CircleException {
        if (r < 0)
            throw new CircleException(r);
        else
            radius = r;

    }

    public void show() {
        System.out.println("圆面积=" + 3.14 * radius * radius);
    }
}

public class App9_8 {
    public static void main(String[] args) {
        Circle cir = new Circle();
        try {
            cir.setRadius(-2.0);
        } catch (CircleException e) {
            System.out.println(e.toString());
        }
    }
}
```

用这个例子理解一下,很快就明白了...  哈哈  
